### ISSUE TITLE
Track is not shown in jbrowse 1.12.3-release

### ISSUE THREAD

**Issue by nauer** [bhofmei/jbplugin-motifdens#1]
Hi, if I try the motif density plugin as described in the *README* it does not show the track. After some investigation I found out that there is a typo in the *README* for the `type`.

I changed the `trackList.json` entry from
```
{  
    "key" : "Nucleotide Density",
    "label" : "nuc_dens",
    "storeClass" : "JBrowse/Store/SeqFeature/SequenceChunks",
    "type": "NucleotideDensityPlugin/View/Track/NucleotideDensity",
    "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
    "motifs" : ["CG", "CHG", "CHH", "C"]
}
```
to
```
{  
    "key" : "Nucleotide Density",
    "label" : "nuc_dens",
    "storeClass" : "JBrowse/Store/SeqFeature/SequenceChunks",
    "type": "MotifDensityPlugin/View/Track/MotifDensity",
    "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
    "motifs" : ["CG", "CHG", "CHH", "C"]
}
```

Now it shows me the track headers but still no content. Maybe another typo?

**Comment by bhofmei** [comment]
Thank you for catching those typos! That was a copy-paste error that I’ve corrected now.

Does the test data work? You can access it by setting the data parameter to be “plugins/MotifDensityPlugin/test/data”.

**Comment by nauer** [comment]
No, it looks like that
![screenshot-2017-11-3 cgr picr assembly chr5 20002 30002](https://user-images.githubusercontent.com/2812806/32375680-cdea0b4a-c0a2-11e7-8627-adc0ec4d12f8.png)

**Comment by bhofmei** [comment]
That’s really frustrating. I’m really sorry about this.

If you are using chrome, can you see if there are any errors being thrown? (right-click anywhere, choose “Inspect”, then go to the “Console” tab)

**Comment by nauer** [comment]
![screenshot from 2017-11-03 14-41-22](https://user-images.githubusercontent.com/2812806/32376497-3b188820-c0a5-11e7-9b2d-81ffe8aee8c8.png)

**Comment by bhofmei** [comment]
I think I know the problem. You fixed by typo but JBrowse cache’s configurations so it’s still using the old configuration. Clearing the cache should work. Easiest way to do that is to go to the “Network” tab, check “Disable cache”, then refresh the page.

The test data still won’t work until you do a git pull to get the updated test data track list. It had the same typos that were in the README.

**Comment by nauer** [comment]
No, I cleared the cache and removed all cookies. Does not work.

Pulling down your updates your test data work. Unfortunately, it does not work for my data.

This is my `trackList.json ` file. Maybe you can find the error.
```
{
  "tracks": [
    {
      "key": "Reference sequence",
      "label": "DNA",
      "type": "SequenceTrack",
      "urlTemplate": "seq/{refseq_dirpath}/{refseq}-",
      "storeClass": "JBrowse/Store/Sequence/StaticChunked",
      "category": "Reference sequence",
      "chunkSize": 20000,
      "seqType": "dna"
    },
    {
      "key" : "Nucleotide Density",
      "label" : "nuc_dens",
      "storeClass" : "JBrowse/Store/SeqFeature/SequenceChunks",
      "type": "MotifDensityPlugin/View/Track/MotifDensity",
      "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
      "motifs" : ["CG", "CHG", "CHH", "C"]
    }
  ],
  "formatVersion": 1,
  "names": {
    "url": "names/",
    "type": "Hash"
  },
  "dataset_id": "chr_1"
}
```

**Comment by bhofmei** [comment]
With no errors being thrown? This is annoying. The trackList.json file looks fine to me.

Does it still show the track headers? If so, can you access the “Track options” dialog at all? 

The other thing I can think of is that there is a known problem where it crashes when zoomed too far out. (It’s on the to-do list) Any chance that’s the issue?

**Comment by nauer** [comment]
Okay, I have now removed all tracks except the sequence and the motif density plugin. Now it seems to work but it so slow that actually the scripts stops. See image:
![jbrowse_failed](https://user-images.githubusercontent.com/2812806/32383795-462f8420-c0b9-11e7-8ade-0febd6d64715.png)

So I checked with a colleague her installation of the plugin. We found out that the plugin works quite fine with her version of jbrowse 1.12.0 but the same data with 1.12.3 took also ages.

It seems that the jbrowse  version affects your plugin. Tomorrow, I will try with version 1.12.0, too.

**Comment by bhofmei** [comment]
The amount of time is highly dependent on the range you are viewing and the number of motifs. Once it loads though, scrolling should be quicker. I’ll work on updating that on Sunday to load faster across wide regions.
I’m not sure why the jbrowse version is giving you a hard time. I personally use v1.12.3

Brigitte

**Comment by nauer** [comment]
Okay, I tested now with release 1.12.0. It is better but still very slow. It depends on the sequence length as you already have mentioned. 

For example if the first scaffold with a length of 80584097 bases is loaded it took so long that the script stopped in between.

Is it possible to pre-calculate the track and then simply load it into the browser?

**Comment by bhofmei** [comment]
It's definitely possible pre-calculate using a custom script and BigWig file. Motifs, window size, and window delta would not be able to be adjusted/configured in the browser though. If you are interested in this, I suggest looking at the [multibigwig](https://github.com/elsiklab/multibigwig) plugin for as the track type.

Yesterday, I did update this plugin to address some of the problems with slow loading/crashing. There is a `maxFeatureScreen` parameter now (default 2500). When the number of density features for a view region is greater than this value, it adjusts the window size/delta values to have this many features. When you zoom in, it uses the configured window size/delta again.

For example, for a region of length 50 MB, window size 100 bp, window delta 10 bp, 5000 features would be created (feature number = region length / window delta). The plugin will temporarily set window size to 200 bp and window delta to 20 bp so only 2500 features are created. It can still be slow for large regions since it has to iterate over the entire region to compute densities, but it won't crash.

You can disable this with `"forceExactWindowSize": true`. Now when the number of features is too large, it gives a warning message to zoom in.

Does this help?

**Comment by nauer** [comment]
With `"forceExactWindowSize": true` I can not see a difference. I see 7000000 bases without a zoom in message. Maybe a typo?

**Comment by bhofmei** [comment]
It’s working for me. Don’t forget to clear your cache. You can also try setting "maxFeatureScreen": 1000.

**Comment by nauer** [comment]
Great job! Now it works pretty well.

Thanks a lot and greetings from Austria
